<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Order Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'hello@printright.ph',
		'to' => 'hello@printright.ph'
	),
	'fields' => array(
		'custom_U356' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U858' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '5R (5x7\")',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'5R (5x7\")\' is required.'
			)
		),
		'custom_U874' => array(
			'order' => 5,
			'type' => 'string',
			'label' => '8R (8x10\")',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'8R (8x10\")\' is required.'
			)
		),
		'custom_U890' => array(
			'order' => 6,
			'type' => 'string',
			'label' => '8x12\"',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'8x12\"\' is required.'
			)
		),
		'custom_U1020' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Photo Gallery Link (Google Drive, Dropbox, etc)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Photo Gallery Link (Google Drive, Dropbox, etc)\' is required.'
			)
		),
		'custom_U1036' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'I do not have Google Drive/Dropbox. Please send me a link where I can upload my photos',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'I do not have Google Drive/Dropbox. Please send me a link where I can upload my photos\' is required.'
			)
		),
		'custom_U1118' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Street',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Street\' is required.'
			)
		),
		'custom_U1130' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U1164' => array(
			'order' => 2,
			'type' => 'string',
			'label' => '4R (4x6\")',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'4R (4x6\")\' is required.'
			)
		)
	)
);

process_form($form);
?>
